import test from "node:test";
import assert from "node:assert/strict";
import { Engine } from "../packages/engine/src/index.ts";
import { conversationSchema, type MessagingCommand } from "../packages/contracts/src/messaging.ts";
import { patientConversation } from "../packages/engine/src/messaging.ts";
import { upgradeMessagingWorld } from "../packages/engine/src/messaging-seed.ts";
test("Practice messaging keeps delivery history and patient replies separate from private notes", () => {
  const e = new Engine();
  const input = { type: "messaging_action", patientId: "SIM-000020", messagingCommand: { kind: "create", subject: "Appointment request", body: "Please reply with your preferred time", channel: "sms", allowReply: true } };
  let r = e.action("default", "gp", input, "Message team", "create-message");
  assert.equal(e.action("default", "gp", input, "Message team", "create-message").id, r.id);
  const command = (command: MessagingCommand, site: "gp" | "patient" = "gp") => e.action("default", site, { type: "messaging_action", patientId: "SIM-000020", resourceId: r.id, expectedVersion: r.version, messagingCommand: command }, "Message team");
  assert.equal(conversationSchema.parse(r.data).entries[0]?.body, "Please reply with your preferred time");
  assert.deepEqual(patientConversation(r).data.entries, []);
  assert.throws(() => command({ kind: "reply", body: "Afternoon" }, "patient"), /delivered/);
  r = command({ kind: "delivery", entryId: `${r.id}-1`, status: "failed" });
  r = command({ kind: "retry", entryId: `${r.id}-1` });
  r = command({ kind: "delivery", entryId: `${r.id}-1`, status: "delivered" });
  const outgoing = conversationSchema.parse(r.data).entries[0];
  assert.equal(outgoing?.direction, "outgoing");
  if (outgoing?.direction === "outgoing") assert.deepEqual(outgoing.delivery.map(event => event.status), ["queued", "failed", "queued", "delivered"]);
  r = command({ kind: "note", body: "Private administrative discussion" });
  assert.equal(JSON.stringify(patientConversation(r)).includes("Private administrative discussion"), false);
  r = command({ kind: "reply", body: "Afternoon please" }, "patient");
  assert.equal(conversationSchema.parse(r.data).entries.at(-1)?.direction, "incoming");
  r = command({ kind: "assign", assignee: "Dr Rowan Page" });
  assert.equal(r.data.assignee, "Dr Rowan Page");
  r = command({ kind: "complete" });
  assert.equal(r.status, "done");
  assert.throws(() => command({ kind: "send", channel: "sms", body: "Another" }), /Reopen/);
  r = command({ kind: "reopen" });
  assert.equal(r.status, "open");
  assert.equal(r.provenance?.created?.actor.name, "Message team");
  assert.equal(conversationSchema.parse(r.data).entries[0]?.body, "Please reply with your preferred time");
});
test("Messaging enforces patient, service, version and world boundaries", () => {
  const e = new Engine(); e.create("separate");
  const r = e.action("default", "gp", { type: "messaging_action", patientId: "SIM-000020", messagingCommand: { kind: "create", subject: "One way", body: "Form ready", channel: "email", allowReply: false } }, "Practice");
  const input = { type: "messaging_action", resourceId: r.id, expectedVersion: r.version, patientId: "SIM-000020", messagingCommand: { kind: "reply", body: "Reply" } };
  assert.throws(() => e.action("default", "patient", input, "Patient"), /Replies are disabled/);
  assert.throws(() => e.action("default", "patient", { ...input, patientId: "SIM-000021" }, "Patient"), /owns this conversation/);
  assert.throws(() => e.action("default", "gp", { ...input, expectedVersion: 100 }, "Practice"), /Stale/);
  assert.throws(() => e.action("separate", "gp", input, "Other"), /Unknown resource/);
  assert.throws(() => e.action("default", "hospital", input, "Hospital"), /not visible/);
  assert.throws(() => e.action("default", "gp", { type: "share_record", resourceId: r.id, target: "hospital" }, "Practice"), /messaging workflow/);
  assert.throws(() => e.action("default", "patient", { ...input, messagingCommand: { kind: "note", body: "Not allowed" } }, "Patient"), /only reply/);
});
test("Templates persist edits and archive while messaging migration remains additive", () => {
  const e = new Engine();
  let r = e.action("default", "gp", { type: "messaging_action", messagingCommand: { kind: "save_template", title: "Collection", body: "Ready at reception", channel: "sms" } }, "Practice");
  r = e.action("default", "gp", { type: "messaging_action", resourceId: r.id, expectedVersion: r.version, messagingCommand: { kind: "save_template", title: "Collection details", body: "Please ask reception", channel: "email" } }, "Practice");
  assert.equal(r.data.body, "Please ask reception");
  r = e.action("default", "gp", { type: "messaging_action", resourceId: r.id, expectedVersion: r.version, messagingCommand: { kind: "archive_template" } }, "Practice");
  assert.equal(r.status, "archived");
  const world = e.require("default");
  const migrated = upgradeMessagingWorld({ ...world, counters: { ...world.counters, messagingVersion: 0 } });
  assert.equal(migrated.resources.length, world.resources.length);
  assert.equal(migrated.resources.find(item => item.id === r.id), world.resources.find(item => item.id === r.id));
  assert.equal(upgradeMessagingWorld(migrated), migrated);
});
