import { z } from "zod";
import { actionSchema, activeServices, scenarios, sites } from "../../../packages/contracts/src/index.ts";
import { hospitalNoteSchema } from "../../../packages/contracts/src/clinical-notes.ts";
import { medicationOrderSchema, bloodTestOrderSchema } from "../../../packages/contracts/src/clinical-orders.ts";
import { catalogue } from "../../../packages/nhs-mocks/src/index.ts";
import { cis2SettingsSchema } from "../../../packages/nhs-mocks/src/cis2.ts";

type Schema = Record<string, unknown>;
const string = { type: "string" };
const integer = { type: "integer" };
const boolean = { type: "boolean" };
const timestamp = { type: "number", description: "Simulation Unix timestamp in milliseconds." };
const ref = (name: string) => ({ $ref: `#/components/schemas/${name}` });
const array = (items: Schema) => ({ type: "array", items });
const object = (properties: Record<string, Schema>, required = Object.keys(properties)): Schema => ({ type: "object", properties, required });
const jsonSchema = (schema: z.ZodType) => {
  const { $schema, ...result } = z.toJSONSchema(schema, { io: "input" });
  return result;
};
const parameter = (name: string, schema: Schema, description: string, required = false, location = "query") => ({ name, in: location, required, description, schema });
const worldParameter = parameter("world", { ...string, default: "default" }, "Operator only: world to inspect or mutate. Team keys always use their own world.");
const idempotency = parameter("Idempotency-Key", string, "Stable unique value for retries of the same action. Reuse it after an uncertain response; use a new value for a new action. Takes precedence over body clientRequestId.", false, "header");
const teamSecurity = [{ TeamKey: [] }, { OperatorKey: [] }, { BrowserSession: [] }];
const operatorSecurity = [{ OperatorKey: [] }];
const response = (schema: Schema, description = "Success", media = "application/json") => ({ description, content: { [media]: { schema } } });
const errors = Object.fromEntries([400, 401, 403, 404, 409, 413, 429, 500].map(status => [String(status), response(ref("Error"), ({ 400: "Invalid input or unsupported workflow", 401: "Missing or invalid credentials", 403: "Scope, origin or operator restriction", 404: "Unknown resource", 409: "Stale version, invalid transition or unavailable capacity", 413: "Request exceeds 65,536 characters", 429: "Deployment has reached its 5,000-team capacity", 500: "Internal simulation error" })[status]) ]));
const body = (schema: Schema, examples?: Record<string, { summary: string; value: unknown }>, media = "application/json") => ({ required: true, content: { [media]: { schema, ...(examples ? { examples } : {}) } } });
type Operation = { operationId: string; tags: string[]; summary: string; description?: string; security?: object[]; parameters?: object[]; requestBody?: object; responses: Record<string, unknown>; deprecated?: boolean };
const paths: Record<string, Record<string, Operation>> = {};
function add(path: string, method: string, operation: Operation) { (paths[path] ??= {})[method] = operation; }
function read(path: string, operationId: string, tag: string, summary: string, schema: Schema, options: Partial<Operation> = {}) {
  add(path, "get", { operationId, tags: [tag], summary, security: teamSecurity, responses: { ...errors, "200": response(schema) }, ...options });
}
function write(path: string, operationId: string, tag: string, summary: string, request: object, schema: Schema, options: Partial<Operation> = {}, method = "post") {
  add(path, method, { operationId, tags: [tag], summary, security: teamSecurity, requestBody: request, responses: { ...errors, "200": response(schema) }, ...options });
}
const siteIds = activeServices.filter(site => site !== "legacy");
const siteParameter = parameter("site", { type: "string", enum: siteIds, default: "gp" }, "Service scope. control requires an operator token. legacy is browser-only.", true, "path");
const patientParameter = parameter("patient", { ...string, example: "SIM-000006" }, "Exact synthetic patient ID. Site view also includes service resources without a patient.");
const patientIdParameter = parameter("patientId", { ...string, example: "SIM-000006" }, "Exact synthetic patient ID.", true);
const schemas: Record<string, Schema> = {
  Error: object({ error: string, message: string }, ["error"]),
  Action: { ...jsonSchema(actionSchema), description: "Executable request fields from the runtime Zod contract. Conditional requirements and clinical workflow transitions are also checked by the engine. Use the named examples as a starting point, choose a permitted site, and copy current resource IDs/versions from a workspace response. All drug prices are integer pence. No clinical advice is provided." },
  HospitalNote: jsonSchema(hospitalNoteSchema), MedicationOrder: jsonSchema(medicationOrderSchema), BloodTestOrder: jsonSchema(bloodTestOrderSchema),
  Patient: object({ id: string, name: string, birthDate: { type: "string", format: "date" }, localIds: { type: "object", additionalProperties: string }, conditions: array(string), needs: array(string), goals: array(string), synthetic: { const: true } }),
  RecordChange: object({ actor: object({ kind: { enum: ["team", "operator", "simulation"] }, name: string }), source: string, action: string, time: timestamp, version: integer }),
  Resource: object({ id: string, patientId: string, kind: string, title: string, status: string, owner: string, visibleTo: array(string), priority: { enum: ["routine", "urgent"] }, createdAt: timestamp, dueAt: timestamp, data: { type: "object", additionalProperties: true, description: "Kind-specific payload. Hospital notes, medication orders and blood-test orders use the named schemas; the full workspace payload is returned without projection." }, version: { type: "integer", minimum: 1 }, provenance: object({ created: { anyOf: [ref("RecordChange"), { type: "null" }] }, changes: array(ref("RecordChange")), recovery: { type: "object", additionalProperties: true } }, ["created", "changes"]) }, ["id", "kind", "title", "status", "owner", "visibleTo", "priority", "createdAt", "data", "version"]),
  Event: object({ id: string, time: timestamp, type: string, actor: string, resourceId: string, patientId: string, detail: string, visibleTo: array(string) }, ["id", "time", "type", "actor", "detail", "visibleTo"]),
  Clock: object({ now: timestamp, paused: boolean, speed: { type: "number" }, events: array(ref("Event")) }),
  Workspace: object({ resources: array(ref("Resource")), patients: array(ref("Patient")), now: timestamp }, ["resources", "patients"]),
  View: object({ id: string, now: timestamp, speed: { type: "number" }, paused: boolean, population: integer, counters: { type: "object", additionalProperties: { type: "number" } }, resources: array(ref("Resource")), resourceTotal: integer, resourceOffset: integer, resourceLimit: integer, staffing: object({ doctors: integer, nurses: integer, staffedSpaces: integer, waiting: integer }), faults: { type: "object", additionalProperties: boolean }, events: array(ref("Event")), agents: array(object({ id: string, enabled: boolean })) }, ["id", "now", "speed", "paused", "population", "resources", "resourceTotal", "resourceOffset", "resourceLimit", "events"]),
  Team: object({ team: string, world: string, scopes: array(string) }),
  Key: object({ apiKey: { type: "string", description: "Reusable team key. Joining with the same normalised name returns this key again." }, team: { ...string, description: "Team attribution label; older teams retain their original label." }, teamName: { ...string, description: "Canonical join name: lowercase with all whitespace removed." }, world: string, scopes: array(string), created: { ...boolean, description: "True only when this request created a new world." } }),
  Bundle: object({ resourceType: { const: "Bundle" }, type: { const: "searchset" }, total: integer, link: array(object({ relation: string, url: string })), entry: array(object({ fullUrl: string, resource: { type: "object", additionalProperties: true }, search: object({ mode: { const: "match" } }) }, ["resource"])) }, ["resourceType", "type", "entry"]),
  FhirPatient: object({ resourceType: { const: "Patient" }, id: string, active: boolean, identifier: array(object({ use: string, system: string, value: string })), name: array({ type: "object", additionalProperties: true }), birthDate: { type: "string", format: "date" }, address: array({ type: "object", additionalProperties: true }), telecom: array({ type: "object", additionalProperties: true }), generalPractitioner: array({ type: "object", additionalProperties: true }), meta: { type: "object", additionalProperties: true } }),
  FhirOrganization: object({ resourceType: { const: "Organization" }, id: string, name: string, active: boolean, identifier: array({ type: "object", additionalProperties: true }), type: array({ type: "object", additionalProperties: true }), address: array({ type: "object", additionalProperties: true }), telecom: array({ type: "object", additionalProperties: true }), meta: { type: "object", additionalProperties: true } }),
  OperationOutcome: object({ resourceType: { const: "OperationOutcome" }, issue: array(object({ severity: string, code: string, diagnostics: string })) }),
  Cis2Settings: jsonSchema(cis2SettingsSchema),
  StaffIdentity: object({ sub: string, name: string, role: string, org: string, organisation: string, nhs_sim: { const: true } }),
  Cis2Configuration: object({ scenario: { enum: ["normal", "deny", "unavailable", "expired-session"] }, tokenLifetimeSeconds: integer, clients: array({ type: "object", additionalProperties: true }), identities: array({ type: "object", additionalProperties: true }), storage: string, active: object({ interactions: integer, codes: integer, tokens: integer }) }),
};
export const actionExamples = {
  task: { summary: "Create a GP or hospital task", value: { type: "create_task", patientId: "SIM-000006", title: "Review synthetic discharge correspondence", text: "Check the simulation record and arrange follow-up." } },
  consultation: { summary: "Save a GP consultation", value: { type: "save_consultation", patientId: "SIM-000006", title: "Synthetic telephone review", text: "Fictional review for integration testing.", consultationStatus: "saved" } },
  problem: { summary: "Add a GP problem", value: { type: "save_problem", patientId: "SIM-000006", title: "Synthetic mobility concern", problemStatus: "active" } },
  note: { summary: "Save a hospital note draft (hospital)", value: { type: "hospital_note", patientId: "SIM-000006", title: "Synthetic progress note", hospitalNoteCommand: { kind: "save", template: "free-text", sections: [{ id: "clinical-note", heading: "Clinical note", text: "Fictional record for integration testing." }] } } },
  bloodTest: { summary: "Request a blood test (hospital or GP)", value: { type: "order_test", patientId: "SIM-000006", title: "Full blood count", bloodTestOrder: { panelId: "fbc", panel: "Full blood count", specimen: "EDTA blood", priority: "routine", collection: "now", clinicalDetails: "Synthetic follow-up request." } } },
  supplierOrder: { summary: "Pharmacy: order packs (replace quote ID/version; meet its minimumPacks)", value: { type: "place_pharmacy_order", resourceId: "REPLACE_WITH_PHARMACY_QUOTE_ID", expectedVersion: 1, quantity: 2 } },
  basketLine: { summary: "Pharmacy: add offer to basket (replace basket/quote IDs and versions; packs must cover requiredUnits)", value: { type: "update_pharmacy_basket", resourceId: "REPLACE_WITH_PHARMACY_BASKET_ID", expectedVersion: 1, quoteId: "REPLACE_WITH_PHARMACY_QUOTE_ID", quoteVersion: 1, quantity: 2, requiredUnits: 1 } },
  checkout: { summary: "Pharmacy: place all basket orders (replace basket ID/latest version; current offers required)", value: { type: "checkout_pharmacy_basket", resourceId: "REPLACE_WITH_PHARMACY_BASKET_ID", expectedVersion: 1 } },
  receiveOrder: { summary: "Pharmacy: receive one pack after dueAt (replace purchase-order ID/latest version)", value: { type: "receive_pharmacy_order", resourceId: "REPLACE_WITH_PHARMACY_ORDER_ID", expectedVersion: 1, quantity: 1, text: "Synthetic delivery reference DEMO-001" } },
  pharmacyReferral: { summary: "Create a fictional Pharmacy First referral (GP, hospital or pharmacy)", value: { type: "receive_pharmacy_referral", patientId: "SIM-000006", title: "Synthetic sore throat referral", pharmacyPathway: "Sore throat", referralSource: "gp" } },
  reviewDischarge: { summary: "GP: review a sent discharge document (replace ID/latest version)", value: { type: "process_document", resourceId: "REPLACE_WITH_SENT_DISCHARGE_SUMMARY_ID", expectedVersion: 1, documentCommand: "review", text: "Synthetic correspondence reviewed; follow-up actions recorded in the simulation." } },
  fileDischarge: { summary: "GP: file a reviewed discharge document (replace ID/latest version after review)", value: { type: "process_document", resourceId: "REPLACE_WITH_REVIEWED_DISCHARGE_SUMMARY_ID", expectedVersion: 1, documentCommand: "file", text: "Filed to the synthetic patient record." } },
  message: { summary: "GP: start a simulated SMS conversation (queued; no real SMS sent)", value: { type: "messaging_action", patientId: "SIM-000006", messagingCommand: { kind: "create", subject: "Simulation follow-up", body: "This is a fictional practice message for integration testing.", channel: "sms", allowReply: true } } },
  deliverMessage: { summary: "GP: mark a queued message delivered (replace conversation ID/version and outgoing entry ID)", value: { type: "messaging_action", resourceId: "REPLACE_WITH_CONVERSATION_ID", expectedVersion: 1, messagingCommand: { kind: "delivery", entryId: "REPLACE_WITH_OUTGOING_ENTRY_ID", status: "delivered" } } },
  patientReply: { summary: "patient site: reply after delivery (replace conversation ID/version; must belong to selected patient)", value: { type: "messaging_action", patientId: "SIM-000006", resourceId: "REPLACE_WITH_CONVERSATION_ID", expectedVersion: 1, messagingCommand: { kind: "reply", body: "Synthetic patient reply for testing." } } },
  prescription: { summary: "Draft a prescription for pharmacy review", value: { type: "draft_prescription", patientId: "SIM-000006", title: "Synthetic medication order", medicationOrder: { drug: "Example medicine", dose: "1", unit: "tablet", route: "Oral", frequency: "Once daily", duration: "7 days", quantity: 7, indication: "Fictional workflow testing; not a prescribing recommendation." } } },
};
read("/healthz", "health", "Discovery", "Check application and PostgreSQL health", object({ ok: boolean, database: { const: "postgresql" }, mode: { const: "synthetic" } }), { security: [] });
read("/api/catalogue", "catalogue", "Discovery", "List live sites, active adapters and simulation incidents", object({ sites: array({ type: "object", additionalProperties: true }), apis: array({ type: "object", additionalProperties: true }), scenarios: array({ type: "object", additionalProperties: true }), identity: object({ issuer: string, clientId: string }), notice: string, documentation: object({ handbook: string, explorer: string, openapi: string }) }), { security: [] });
read("/openapi.json", "openapiAlias", "Discovery", "Download the OpenAPI JSON (alias)", { type: "object", additionalProperties: true }, { security: [] });
read("/api/openapi.json", "openapi", "Discovery", "Download this OpenAPI 3.1 document as JSON", { type: "object", additionalProperties: true }, { security: [] });
write("/api/keys", "createTeam", "Team", "Create or join a team world by name", body(object({ teamName: { ...string, description: "Lowercased with all whitespace removed before validation. The normalised name must contain 2–80 characters." }, site: { type: "string", enum: activeServices.filter(id => !["control", "legacy"].includes(id)) } }, ["teamName"]), { team: { summary: "Create or join a team", value: { teamName: "My integration team" } } }), ref("Key"), { security: [], description: "Creates or joins a persistent world using a lowercase name with all whitespace removed. Anyone who knows the name can join its simulation world. Repeat requests return the same reusable key and world. Older hash-only teams receive a reusable key for their existing world; previous keys remain valid. Ambiguous historical names spanning multiple worlds return 409: use an existing key. Up to 5,000 distinct team worlds; existing teams can rejoin at capacity. No per-IP or time-based throttle. Omit site to create a team with all participant scopes. Rejoining preserves existing scopes. Legacy has no API key scope.", responses: { ...errors, "201": response(ref("Key"), "Team created or joined; copy apiKey"), "501": response(ref("Error"), "Legacy is browser-only") } });
read("/api/team", "team", "Team", "Read the authenticated team and scopes", ref("Team"), { parameters: [worldParameter] });
write("/api/session", "createBrowserSession", "Team", "Create a one-hour browser integration session", body(object({}, [])), object({ ok: boolean }), { security: [{ TeamKey: [] }, { OperatorKey: [] }], description: "Send a bearer token. Sets HttpOnly sim_session cookie for /browser/legacy. Cookie sessions are process-local and expire after one hour; the legacy form supplies its own CSRF field." });
read("/api/clock", "readClock", "Simulation time", "Read time and up to 100 visible recent events", ref("Clock"), { parameters: [worldParameter] });
write("/api/clock", "changeClock", "Simulation time", "Pause, change speed or advance the team world", body(object({ paused: boolean, speed: { type: "number", minimum: 0, maximum: 3600 }, advanceMinutes: { type: "number", minimum: 0, maximum: 10080 } }, []), { advance: { summary: "Run delayed test results", value: { paused: true, advanceMinutes: 121 } } }), ref("Clock"), { parameters: [worldParameter], description: "A real mutation of the current simulation world. Manual advance requires paused:true (set it in the same request if needed); otherwise 409. Advancing time executes due jobs. Clock events and visible action events are returned here; there is no separate event-stream endpoint." });
read("/api/plan-lab", "retiredChallengeWorkbook", "Discovery", "Retired challenge workbook", ref("Error"), { security: [], deprecated: true, responses: { "410": response(object({ error: string, href: string }), "Retired; explore /control/ and service APIs") } });
read("/api/sites/{site}/view", "siteView", "Service workspaces", "Read scoped resources, events and simulation context", ref("View"), { parameters: [ { ...siteParameter, schema: { type: "string", enum: [...siteIds, "patient"], default: "gp" } }, patientParameter, parameter("offset", { type: "integer", minimum: 0, default: 0 }, "Resource page offset."), parameter("limit", { type: "integer", minimum: 1, maximum: 500, default: 500 }, "Resource page size."), worldParameter], description: "Patient portal uses the GP scope and removes staff-only conversation content. patient filtering includes shared service resources with no patient ID." });
read("/api/sites/{site}/patients", "sitePatients", "Service workspaces", "Search the synthetic patient directory", object({ total: integer, items: array(ref("Patient")) }), { parameters: [siteParameter, parameter("q", string, "Name, ID, condition, need or goal search; prefix/full-text matching."), parameter("offset", { type: "integer", minimum: 0, default: 0 }, "Offset; fixed page size 30."), worldParameter] });
write("/api/sites/{site}/actions", "siteAction", "Service workspaces", "Execute a scoped clinical or operational action", body(ref("Action"), actionExamples), ref("Resource"), { parameters: [{ ...siteParameter, schema: { type: "string", enum: [...siteIds, "patient"], default: "gp" } }, idempotency, worldParameter], description: "Persists a change and records team attribution. Action permissions depend on site, resource visibility and current state; not every action type is valid at every site. For editing, use resourceId and the latest expectedVersion. Signed hospital notes accept addenda only. Clinical orders, discharge/document processing, pharmacy stock/supplier/basket operations, appointments and messaging all use this endpoint. See the complete Action schema. CIS2 tokens do not grant team API access." });
read("/api/sites/{site}/appointments", "siteAppointments", "Service workspaces", "Read a day of appointments and appointment sessions", object({ appointments: array(ref("Resource")), patients: array(object({ id: string, name: string })), sessions: array(ref("Resource")) }), { parameters: [siteParameter, parameter("date", { type: "string", format: "date", example: "2026-09-12" }, "UTC calendar day; required and validated.", true), worldParameter] });
for (const [site, workspace, summary, tag] of [
  ["hospital", "attendances", "Read the hospital take, ED and inpatient list", "Hospital"],
  ["hospital", "documents", "Read hospital discharge summaries", "Hospital"],
  ["gp", "documents", "Read discharge correspondence visible to GP", "Primary care"],
  ["pharmacy", "pharmacy-workspace", "Read prescriptions, referrals, products, stock movements, supplier quotes, orders and baskets", "Pharmacy"],
  ["gp", "messaging-workspace", "Read practice conversations and message templates", "Messaging"],
  ["patient", "messaging-workspace", "Read one patient's visible conversations", "Messaging"],
]) read(`/api/sites/${site}/${workspace}`, `${site}_${workspace.replaceAll("-", "_")}`, tag, summary, ref("Workspace"), { parameters: site === "patient" ? [patientIdParameter, worldParameter] : [worldParameter], description: site === "patient" ? "Requires GP scope. Staff-only entries and empty conversations are excluded." : "Mutations use the site actions endpoint; no separate CRUD endpoints are provided." });
for (const api of catalogue) {
  read(`/api/nhs/${api.id}`, `adapter_${api.id.replaceAll("-", "_")}`, "NHS-shaped adapters", api.name, ref("Bundle"), { parameters: [patientParameter, parameter("q", string, "Alias for patient. PDS searches demographics; most other adapters filter exact patient ID. ODS/DoS return their fixed fictional directory."), worldParameter], description: `${api.description}. Requires ${api.site} scope. Simplified JSON projection, not a certified NHS API or full FHIR implementation. At most 100 workflow resources are returned; total may be larger. PDS/ODS FHIR search/read routes are documented separately.` });
  write(`/api/nhs/${api.id}/actions`, `adapter_${api.id.replaceAll("-", "_")}_action`, "NHS-shaped adapters", `Submit an action through ${api.name}`, body(ref("Action")), ref("Resource"), { parameters: [idempotency, worldParameter], description: `Delegates to the ${api.site} site action engine with that scope and its existing permissions. This is the simulator's action envelope, not the production NHS API's write protocol.` });
}
for (const [adapter, resource, scope] of [["pds", "Patient", "gp"], ["ods", "Organization", "referrals"]]) {
  const fhirErrors = Object.fromEntries([400, 401, 403, 404, 405].map(status => [String(status), response(ref("OperationOutcome"), "FHIR-shaped error response", "application/fhir+json")]));
  const fhirOptions = (schema: Schema): Partial<Operation> => ({ description: `Read-only FHIR R4-shaped subset; requires ${scope} scope. Uses local SIM identifiers, not NHS numbers/ODS codes. No NHS profile validation, fuzzy tracing, record updates or real network access. Unsupported, repeated or empty query parameters return 400.`, responses: { ...fhirErrors, "200": response(schema, "Synthetic FHIR-shaped result", "application/fhir+json") } });
  read(`/api/nhs/${adapter}/metadata`, `${adapter}Capability`, "FHIR read-only subsets", `${resource} capability statement`, { type: "object", additionalProperties: true }, { ...fhirOptions({ type: "object", additionalProperties: true }), description: `Local subset capabilities. Requires ${scope} scope. No query parameters are accepted, including world.` });
  const search = resource === "Patient" ? [parameter("family", string, "Case-insensitive family-name prefix."), parameter("given", string, "Case-insensitive given-name prefix."), parameter("birthdate", { type: "string", format: "date" }, "Exact valid date; no FHIR date prefixes.")] : [parameter("name", string, "Case-insensitive organisation-name prefix."), parameter("active", { type: "string", enum: ["true", "false"] }, "All synthetic organisations are active; false returns none.")];
  read(`/api/nhs/${adapter}/${resource}`, `${adapter}Search`, "FHIR read-only subsets", `Search synthetic ${resource} records`, ref("Bundle"), { ...fhirOptions(ref("Bundle")), parameters: [...search, parameter("identifier", string, "Exact value or system|value. Patient system https://nhs-sim.example/identifier/patient; organisation system https://nhs-sim.example/identifier/organisation."), parameter("_count", { type: "integer", minimum: 1, maximum: 100, default: 20 }, "Page size."), parameter("_offset", { type: "integer", minimum: 0, default: 0 }, "Local offset extension; not a production API claim.")] });
  read(`/api/nhs/${adapter}/${resource}/{id}`, `${adapter}Read`, "FHIR read-only subsets", `Read one synthetic ${resource}`, ref(`Fhir${resource}`), { ...fhirOptions(ref(`Fhir${resource}`)), parameters: [parameter("id", { type: "string", pattern: resource === "Patient" ? "^SIM-\\d{6}$" : "^SIM-[A-Z]+$", example: resource === "Patient" ? "SIM-000006" : "SIM-RIVERSIDE" }, "Local identifier. Read accepts no query parameters.", true, "path")] });
}
read("/api/control/worlds", "worlds", "Operator", "List simulation world IDs", array(string), { security: operatorSecurity });
read("/api/control/snapshot", "snapshot", "Operator", "Read the full world and event history", object({ world: { type: "object", additionalProperties: true }, events: array(ref("Event")) }), { security: operatorSecurity, parameters: [worldParameter], description: "May be large for a published population. Prefer paged site views for participant applications." });
for (const [path, name, summary, input, result] of [
  ["incidents", "setIncident", "Enable or disable a simulation incident", object({ id: { type: "string", enum: scenarios.map(s => s.id) }, enabled: boolean }), { type: "object", additionalProperties: true }],
  ["agents", "setAgent", "Enable or disable a simulation agent", object({ id: string, enabled: boolean }), object({ id: string, enabled: boolean })],
  ["model-propose", "proposeModelActions", "Request model action proposals without executing them", object({}, []), object({ proposals: array({ type: "object", additionalProperties: true }), note: string })],
  ["population", "generatePopulation", "Add one deterministic population batch", object({ target: { type: "integer", minimum: 8, maximum: 50000 }, batchSize: { type: "integer", minimum: 1, maximum: 1000, default: 500 } }, ["target"]), object({ world: string, population: integer, resources: integer, target: integer, complete: boolean, generator: string })],
  ["population/publish", "publishPopulation", "Publish this world's population as a baseline", object({}, []), object({ world: string, published: boolean })],
  ["population/attach", "attachPopulation", "Attach a published source population to this world", object({ source: { ...string, default: "default" } }, []), object({ world: string, population: integer })],
] satisfies [string, string, string, Schema, Schema][]) write(`/api/control/${path}`, name, "Operator", summary, body(input), result, { security: operatorSecurity, parameters: [worldParameter] });
read("/api/operator/cis2", "cis2Configuration", "CIS-too identity", "Read identity simulator settings and active counts", ref("Cis2Configuration"), { security: operatorSecurity });
write("/api/operator/cis2", "configureCis2", "CIS-too identity", "Replace identity settings and revoke existing sessions", body(ref("Cis2Settings")), ref("Cis2Configuration"), { security: operatorSecurity, description: "Requires the operator bearer header, not a browser session. Settings are process-local; restart restores defaults. Client IDs and redirect URIs must be unique. Redirects must use HTTPS or localhost HTTP, with no credentials or fragment." }, "put");
add("/api/operator/cis2", "delete", { operationId: "revokeCis2", tags: ["CIS-too identity"], summary: "Revoke all codes, interactions and identity tokens", security: operatorSecurity, responses: { ...errors, "200": response(ref("Cis2Configuration")) } });
read("/cis2/.well-known/openid-configuration", "oidcDiscovery", "CIS-too identity", "Read OpenID Connect discovery metadata", { type: "object", additionalProperties: true }, { security: [] });
read("/cis2/jwks", "oidcJwks", "CIS-too identity", "Read the current RS256 public signing key", object({ keys: array({ type: "object", additionalProperties: true }) }), { security: [] });
read("/cis2/session", "staffSession", "CIS-too identity", "Read the browser's simulated staff identity", object({ identity: { anyOf: [ref("StaffIdentity"), { type: "null" }] } }), { security: [], description: "Reads HttpOnly cis2_staff cookie scoped to /cis2/. Returns identity:null when absent or expired; team API keys are unrelated." });
read("/cis2/userinfo", "oidcUserinfo", "CIS-too identity", "Read claims for a simulated identity access token", ref("StaffIdentity"), { security: [{ CIS2AccessToken: [] }] });
read("/cis2/authorize", "oidcAuthorize", "CIS-too identity", "Begin browser authorization and choose fictional staff/role", string, { security: [], parameters: [parameter("client_id", { ...string, example: "nhs-sim-client" }, "Registered client ID.", true), parameter("redirect_uri", { type: "string", format: "uri" }, "Exact registered callback URL.", true), parameter("response_type", { const: "code" }, "Authorization code only.", true), parameter("scope", { ...string, default: "openid profile" }, "openid required; only openid/profile supported."), parameter("code_challenge", { ...string, pattern: "^[A-Za-z0-9_-]{43}$" }, "Base64url SHA256 hash of your verifier.", true), parameter("code_challenge_method", { const: "S256" }, "S256 only.", true), parameter("state", { ...string, minLength: 1, maxLength: 512 }, "Client state; check at callback.", true), parameter("nonce", { ...string, minLength: 1, maxLength: 512 }, "Nonce included in ID token.", true), parameter("signin_method", { enum: ["smartcard", "security-key"] }, "Presentation only; no physical credential is accessed.")], responses: { ...errors, "200": response(string, "HTML consent form; open in a browser to continue", "text/html") }, description: "Use a browser for consent, not a background HTTP client. Sets cis2_interaction cookie and displays CSRF-protected staff selection. /cis2/ provides a working demonstration; /cis2/callback completes it." });
write("/cis2/authorize", "oidcConsent", "CIS-too identity", "Complete the browser consent interaction", body(object({ interaction: string, csrf: string, identity: string, assignment: string, action: { enum: ["continue", "cancel"] } }), undefined, "application/x-www-form-urlencoded"), object({ redirect: string }), { security: [], parameters: [parameter("Accept", { type: "string", default: "application/json" }, "Use application/json to receive redirect JSON; otherwise returns HTTP 303.", false, "header")], description: "Requires the matching cis2_interaction browser cookie and hidden fields from the HTML authorization form. Do not fabricate these values. One-use authorization codes expire after two minutes.", responses: { ...errors, "200": response(object({ redirect: string })), "303": { description: "Redirect to registered callback with code/state or an error", headers: { Location: { schema: string } } } } });
write("/cis2/token", "oidcToken", "CIS-too identity", "Exchange a one-use authorization code with PKCE", body(object({ grant_type: { const: "authorization_code" }, client_id: string, redirect_uri: { type: "string", format: "uri" }, code: string, code_verifier: { type: "string", pattern: "^[A-Za-z0-9._~-]{43,128}$" } }), undefined, "application/x-www-form-urlencoded"), object({ access_token: string, id_token: string, token_type: { const: "Bearer" }, expires_in: integer, scope: string }), { security: [], description: "Public client; no client secret or refresh token. Wrong verifier consumes the code. Returns opaque access token plus RS256 ID token and sets a staff-session cookie. Tokens cannot authenticate service APIs." });

export const openApiDocument = {
  openapi: "3.1.0",
  info: { title: "NHS-SIM API", version: "1.0.0", description: "Synthetic healthcare simulation APIs. Start with POST /api/keys, copy apiKey, then authorize using TeamKey. Try it out performs real changes within your team's simulated world. No real patient data, NHS credentials or clinical advice. CIS-too identity access tokens and operator tokens are separate credentials. JSON request bodies are limited to 65,536 characters. Site actions use optimistic versions and idempotency. Browser origin checks permit only the deployed application origin for mutations. Legacy HTML form integration is documented in the handbook and has no REST action API." },
  servers: [{ url: "/", description: "This deployment (same origin)" }],
  tags: ["Discovery", "Team", "Service workspaces", "Primary care", "Hospital", "Pharmacy", "Messaging", "Simulation time", "NHS-shaped adapters", "FHIR read-only subsets", "CIS-too identity", "Operator"].map(name => ({ name })),
  paths,
  components: { securitySchemes: { TeamKey: { type: "http", scheme: "bearer", description: "apiKey returned by POST /api/keys; scoped to one team world." }, OperatorKey: { type: "http", scheme: "bearer", description: "Deployment OPERATOR_TOKEN, for organisers only." }, BrowserSession: { type: "apiKey", in: "cookie", name: "sim_session", description: "HttpOnly session established by POST /api/session; browsers manage it." }, CIS2AccessToken: { type: "http", scheme: "bearer", description: "Opaque access_token from /cis2/token; identity userinfo only, not a team key." } }, schemas },
  "x-site-registry": sites.map(site => ({ id: site.id, name: site.name })),
};
