import React, { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { Action, Patient, Resource } from "../../contracts/src/index.ts";
import { hospitalAttendances, hospitalMetrics } from "../../contracts/src/hospital.ts";
import type { WorkflowApi } from "./gp-workflows.tsx";
import { RecordAttribution } from "./record-attribution.tsx";
import "./hospital-tracking.css";

const stamp = (n: number) => new Date(n).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit", timeZone: "UTC" });
const lists = ["A&E tracking", "Medical take", "Inpatient census", "Discharged"] as const;
type TrackingList = typeof lists[number];
const stageLabels = { waiting: "Waiting for assessment", assessing: "Assessment in progress", take: "Awaiting medical take", inpatient: "Admitted", discharged: "Discharged" };
export function HospitalTracking({ api, worldId, openPatient, urgentOnly = false }: { api: WorkflowApi; worldId: string; urgentOnly?: boolean; openPatient: (id: string) => void }) {
  const client = useQueryClient();
  const [list, setList] = useState<TrackingList>("A&E tracking");
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState("");
  const [register, setRegister] = useState(false);
  const [patientQuery, setPatientQuery] = useState("");
  const [patientId, setPatientId] = useState("");
  const [complaint, setComplaint] = useState("");
  const [location, setLocation] = useState("Waiting room");
  const [clinician, setClinician] = useState("");
  const [acuity, setAcuity] = useState<Action["acuity"]>("3");
  const [disposition, setDisposition] = useState("");
  const [notice, setNotice] = useState("");
  const tracking = useQuery({ queryKey: ["hospital-tracking", worldId], queryFn: () => api<{ resources: Resource[]; patients: Patient[]; now: number }>("/api/sites/hospital/attendances"), refetchInterval: 5000 });
  const matches = useQuery({ queryKey: ["hospital-registration", worldId, patientQuery], queryFn: () => api<{ items: Patient[] }>("/api/sites/hospital/patients?q=" + encodeURIComponent(patientQuery)), enabled: register });
  const change = useMutation({ mutationFn: (action: Action) => api<Resource>("/api/sites/hospital/actions", action), onSuccess: async (resource) => { setNotice("Saved to this team's hospital. " + stageLabels[hospitalAttendances([resource])[0].attendance.stage] + "."); setRegister(false); await client.invalidateQueries(); }, onError: (e) => setNotice(e.message) });
  const rows = hospitalAttendances(tracking.data?.resources ?? []);
  const now = tracking.data?.now ?? 0;
  const metrics = hospitalMetrics(tracking.data?.resources ?? [], now);
  const inList = (stage: string, name: TrackingList) => name === "A&E tracking" ? ["waiting", "assessing", "take"].includes(stage) : name === "Medical take" ? stage === "take" : name === "Inpatient census" ? stage === "inpatient" : stage === "discharged";
  const name = (id?: string) => tracking.data?.patients.find((p) => p.id === id)?.name ?? id ?? "Unknown patient";
  const visible = rows.filter(({ resource, attendance }) => inList(attendance.stage, list) && (!urgentOnly || ["1", "2"].includes(attendance.acuity)) && `${name(resource.patientId)} ${resource.patientId} ${attendance.presentingComplaint} ${attendance.location} ${attendance.clinician}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => a.attendance.arrivalAt - b.attendance.arrivalAt);
  const current = rows.find(({ resource }) => resource.id === selected);
  function select(resource: Resource) { const attendance = hospitalAttendances([resource])[0].attendance; setSelected(resource.id); setLocation(attendance.location); setClinician(attendance.clinician === "Unassigned" ? "" : attendance.clinician); setAcuity(attendance.acuity); setDisposition(""); setNotice(""); }
  function command(hospitalCommand: Action["hospitalCommand"]) { if (current) change.mutate({ type: "update_attendance", resourceId: current.resource.id, expectedVersion: current.resource.version, hospitalCommand, clinician: clinician.trim() || undefined, location, acuity, disposition: disposition.trim() || undefined }); }
  return <div className="millennium-tracking">
    <div className="tracking-menubar"><b>Patient List Manager</b><span>Clinical operations workspace</span><span>Northbank General</span></div>
    <div className="tracking-commandbar"><button onClick={() => { setSelected(""); setRegister(true); setPatientId(""); setComplaint(""); setLocation("Waiting room"); setClinician(""); setAcuity("3"); }}>✚ Register A&E attendance</button><button onClick={() => { void tracking.refetch(); }}>↻ Refresh lists</button><label>Find in list <input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Patient, location or clinician" /></label><time>Simulation · {stamp(now)}</time></div>
    <div className="tracking-workspace"><nav aria-label="Hospital patient lists"><h3>Patient lists</h3><small>Northbank General</small>{lists.map((item) => <button key={item} aria-current={list === item ? "page" : undefined} onClick={() => { setList(item); setSelected(""); }}>{item}<b>{rows.filter(({ attendance }) => inList(attendance.stage, item)).length}</b></button>)}<p>Double-check the patient and encounter before entering the chart.</p></nav>
    <main><div className="tracking-tab">{list} <span>×</span></div><div className="tracking-metrics"><span>Arrivals today <b>{metrics.arrivalsToday}</b></span><span>Waiting for assessment <b>{metrics.waiting}</b></span><span>Current mean wait <b>{metrics.averageWait === null ? "—" : metrics.averageWait + " min"}</b></span><span>Mean assessment wait · arrivals today <b>{metrics.assessedAverage === null ? "—" : metrics.assessedAverage + " min"}</b></span><span>In A&E ≥4 hours <b>{metrics.overFourHours}</b></span></div>
    {tracking.isError && <p role="alert">{tracking.error.message}</p>}{tracking.isPending && <p>Loading hospital lists…</p>}
    <div className="tracking-grid"><table><thead><tr><th>Location</th><th>Patient / identifier</th><th>Acuity</th><th>Arrival</th><th>Wait to assessment</th><th>Presenting complaint</th><th>Status</th><th>Responsible clinician</th></tr></thead><tbody>{visible.map(({ resource, attendance: a }) => <tr key={resource.id} className={selected === resource.id ? "selected" : ""} onClick={() => select(resource)}><td>{a.location}</td><td><button className="ehr-record-link" onClick={(e) => { e.stopPropagation(); if (resource.patientId) openPatient(resource.patientId); }}>{name(resource.patientId)}</button><small>{resource.patientId}</small></td><td><span className={Number(a.acuity) <= 2 ? "tracking-acuity high" : "tracking-acuity"}>{a.acuity}</span></td><td>{stamp(a.arrivalAt)}</td><td>{"assessmentAt" in a && a.assessmentAt !== null ? Math.round((a.assessmentAt - a.arrivalAt) / 60000) + " min · seen" : a.stage === "discharged" ? "Not assessed" : Math.max(0, Math.round((now - a.arrivalAt) / 60000)) + " min"}</td><td><button className="ehr-record-link" onClick={() => select(resource)}>{a.presentingComplaint}</button></td><td>{stageLabels[a.stage]}</td><td>{a.clinician}</td></tr>)}</tbody></table>{!visible.length && !tracking.isPending && <p>No patients in this list.</p>}</div>
    <footer>{visible.length} encounters · Select a row to manage attendance, or a patient name to open the chart.</footer>
    {current && <section className="tracking-editor" aria-label="Manage attendance"><h3>{name(current.resource.patientId)} · {stageLabels[current.attendance.stage]}</h3><RecordAttribution record={current.resource} history />{current.attendance.stage !== "discharged" ? <><div className="tracking-fields"><label>Responsible clinician<input value={clinician} onChange={(e) => setClinician(e.target.value)} placeholder="Assign a clinician" /></label><label>Location<input value={location} onChange={(e) => setLocation(e.target.value)} /></label><label>Acuity<select value={acuity} onChange={(e) => setAcuity(e.target.value === "1" ? "1" : e.target.value === "2" ? "2" : e.target.value === "4" ? "4" : e.target.value === "5" ? "5" : "3")}>{[1,2,3,4,5].map((n) => <option key={n}>{n}</option>)}</select></label></div><div className="tracking-actions"><button disabled={change.isPending} onClick={() => command("assign")}>Save assignment</button>{current.attendance.stage === "waiting" && <button disabled={change.isPending || !clinician.trim()} onClick={() => command("assess")}>Start assessment</button>}{current.attendance.stage === "assessing" && <button disabled={change.isPending} onClick={() => command("refer")}>Refer to medical take</button>}{current.attendance.stage === "take" && <button disabled={change.isPending || !location.trim()} onClick={() => command("admit")}>Admit to entered location</button>}<label>Discharge outcome<input value={disposition} onChange={(e) => setDisposition(e.target.value)} placeholder="Destination / outcome" /></label><button disabled={change.isPending || !disposition.trim()} onClick={() => command("discharge")}>Discharge</button></div></> : <p>{current.attendance.disposition} · {stamp(current.attendance.dischargedAt)}</p>}</section>}
    {notice && <p role="status" className="tracking-notice">{notice}</p>}
    </main></div>
    {register && <div className="ehr-modal-backdrop"><form className="ehr-modal tracking-registration" onSubmit={(e) => { e.preventDefault(); change.mutate({ type: "register_attendance", patientId, title: complaint, acuity, location, clinician: clinician.trim() || undefined }); }}><h2>Register A&E attendance</h2><label>Find patient<input value={patientQuery} onChange={(e) => setPatientQuery(e.target.value)} placeholder="Name or SIM identifier" /></label><label>Patient<select required value={patientId} onChange={(e) => setPatientId(e.target.value)}><option value="">Choose patient</option>{matches.data?.items.map((p) => <option key={p.id} value={p.id}>{p.name} · {p.id}</option>)}</select></label><label>Presenting complaint<input required maxLength={500} value={complaint} onChange={(e) => setComplaint(e.target.value)} /></label><label>Acuity<select value={acuity} onChange={(e) => setAcuity(e.target.value === "1" ? "1" : e.target.value === "2" ? "2" : e.target.value === "4" ? "4" : e.target.value === "5" ? "5" : "3")}>{[1,2,3,4,5].map((n) => <option key={n}>{n}</option>)}</select></label><label>Location<input required value={location} onChange={(e) => setLocation(e.target.value)} /></label><label>Responsible clinician<input value={clinician} onChange={(e) => setClinician(e.target.value)} placeholder="Optional at registration" /></label>{change.isError && <p role="alert">{change.error.message}</p>}<div><button type="button" onClick={() => setRegister(false)}>Cancel</button><button disabled={change.isPending || !patientId}>Register attendance</button></div></form></div>}
  </div>;
}
