import React, { useState, type CSSProperties } from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider, useQuery, useMutation } from '@tanstack/react-query';
import { createRootRoute, createRoute, createRouter, RouterProvider } from '@tanstack/react-router';
import { sites, type SiteId, type Resource, type Patient, type Action, type SimEvent, scenarios } from '../../contracts/src/index.ts';
import './style.css';

const client=new QueryClient({defaultOptions:{queries:{retry:false}}});
export function mount(siteId:SiteId) {
  const site=sites.find(s=>s.id===siteId)!;
  document.title=site.name+' | NHS-SIM';
  const rootRoute=createRootRoute({component:()=> <Workbench siteId={siteId}/>});
  const index=createRoute({getParentRoute:()=>rootRoute,path:'/'});
  const router=createRouter({routeTree:rootRoute.addChildren([index]),basepath:'/'+siteId});
  createRoot(document.getElementById('root')!).render(<QueryClientProvider client={client}><RouterProvider router={router}/></QueryClientProvider>);
}
type View={now:number;speed:number;paused:boolean;population:number;resources:Resource[];events:SimEvent[];agents?:{id:string;enabled:boolean}[];counters:Record<string,number>;faults?:Record<string,boolean>;staffing:{doctors:number;nurses:number;staffedSpaces:number;waiting:number}};
function Workbench({siteId}:{siteId:SiteId}){
  const site=sites.find(s=>s.id===siteId)!;
  const [key,setKey]=useState(()=>sessionStorage.getItem('sim-key')??'');
  const [team,setTeam]=useState(''),[keyInput,setKeyInput]=useState(''),[search,setSearch]=useState('');
  const [patient,setPatient]=useState(new URLSearchParams(location.search).get('patient')??'');
  const [world,setWorld]=useState('default'),[tab,setTab]=useState<'work'|'apis'>('work'),[browserReady,setBrowserReady]=useState(false);
  const [title,setTitle]=useState(''),[actionType,setActionType]=useState<Action['type']>('create_task');
  const [notice,setNotice]=useState('');
  const suffix=siteId==='control'?'?world='+encodeURIComponent(world):'';
  async function api<T>(path:string,data?:unknown):Promise<T>{
    const response=await fetch(path,{method:data===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(key?{Authorization:'Bearer '+key}:{})},...(data===undefined?{}:{body:JSON.stringify(data)})});
    const result=await response.json();if(!response.ok)throw new Error(result.message??result.error??'Request failed');return result;
  }
  const saveKey=(value:string)=>{sessionStorage.setItem('sim-key',value);setKey(value);client.clear();setNotice('Key saved for this browser session.');};
  const catalogue=useQuery({queryKey:['catalogue'],queryFn:()=>api<{apis:{id:string;name:string;description:string;site:string}[]}>('/api/catalogue')});
  const view=useQuery({queryKey:['view',siteId,key,world],queryFn:()=>api<View>('/api/sites/'+siteId+'/view'+suffix),enabled:!!key&&siteId!=='legacy',refetchInterval:2000});
  const patients=useQuery({queryKey:['patients',siteId,key,search,world],queryFn:()=>api<{items:Patient[];total:number}>('/api/sites/'+(siteId==='legacy'?'gp':siteId)+'/patients?q='+encodeURIComponent(search)+(siteId==='control'?'&world='+encodeURIComponent(world):'')),enabled:!!key&&siteId!=='legacy'});
  const mutation=useMutation({mutationFn:async({path,data}:{path:string;data:unknown})=>api(path,data),onSuccess:()=>{client.invalidateQueries();setNotice('Saved to the simulation.');},onError:e=>setNotice(e.message)});
  const issue=useMutation({mutationFn:()=>api<{apiKey:string;world:string}>('/api/keys',{teamName:team}),onSuccess:r=>{saveKey(r.apiKey);setWorld(r.world);setNotice('Team world created, paused and ready. Open any clinical site. Keep a copy of your key before closing this session.');},onError:e=>setNotice(e.message)});
  const act=(type:Action['type'],r:Resource,target?:SiteId)=>mutation.mutate({path:'/api/sites/'+siteId+'/actions'+suffix,data:{type,resourceId:r.id,expectedVersion:r.version,target}});
  const clock=(data:unknown)=>mutation.mutate({path:'/api/clock'+suffix,data});
  const rows=(view.data?.resources??[]).filter(r=>!patient||r.patientId===patient||!r.patientId);
  const current=patients.data?.items.find(p=>p.id===patient);
  return <div className={'app '+(siteId==='legacy'?'legacy':'')} style={{'--brand':site.color} as CSSProperties}>
    <aside><a className="wordmark" href="/control/">NHS<span>SIM</span><small>NEIGHBOURHOOD LAB</small></a><nav aria-label="Connected systems">{sites.map(s=><a key={s.id} href={'/'+s.id+'/'+(patient?'?patient='+patient:'')} className={s.id===siteId?'active':''}>{s.name}</a>)}</nav><footer>Fictional organisations.<br/>Synthetic people. Real workflows.<br/><strong>Not for clinical use.</strong></footer></aside>
    <main><div className="simulation-banner">SIMULATED ENVIRONMENT · NO REAL PATIENT DATA · ALL PRODUCT NAMES ARE FICTIONAL PARODIES</div>
      <header><div><p className="eyebrow">{site.subtitle}</p><h1>{site.name}</h1></div><div className="header-actions"><button onClick={()=>setTab(tab==='apis'?'work':'apis')}>{tab==='apis'?'Worklists':'Developer desk'}</button>{key&&<button onClick={()=>saveKey('')}>Change key</button>}</div></header>
      {!key&&<section className="panel access"><h2>Enter the neighbourhood</h2><p>Write your team name to receive a key and an isolated, seeded world. No approval queue. No sales call.</p><form onSubmit={e=>{e.preventDefault();issue.mutate();}}><label>Team name<input value={team} onChange={e=>setTeam(e.target.value)} required minLength={2} maxLength={80} placeholder="The Loop Closers"/></label><button disabled={issue.isPending}>Create team & API key</button></form><details><summary>Use an existing team key or operator token</summary><form onSubmit={e=>{e.preventDefault();saveKey(keyInput);}}><label>API key / operator token<input type="password" value={keyInput} onChange={e=>setKeyInput(e.target.value)} required/></label><button>Connect</button></form></details></section>}
      {notice&&<p className="notice" role="status">{notice}</p>}
      {tab==='apis'?<section className="panel"><h2>Developer desk</h2><p>Every endpoint lives on this origin. Send <code>Authorization: Bearer YOUR_KEY</code>. Your key selects your team's world. NHS adapters are simplified local mocks, not certified API replicas.</p>{key&&<details><summary>Reveal team key (keep private)</summary><code className="key">{key}</code></details>}<div className="api-grid">{catalogue.data?.apis.map(a=><article key={a.id}><h3>{a.name}</h3><p>{a.description}</p><code>GET /api/nhs/{a.id}</code><p>Scope: {a.site}</p></article>)}</div><h3>Legacy integration request</h3><button onClick={async()=>{try{await api('/api/keys',{teamName:team||'Demo team',site:'legacy'});}catch(e){setNotice((e as Error).message);}}}>Request vendor API access</button><h3>CIS-too</h3><code>/cis2/.well-known/openid-configuration</code><p>Authorization code + PKCE, signed ID token, JWKS and a fixed fictional clinician. Separate from team API keys.</p></section>:<>
      {siteId==='control'&&key&&<section className="panel"><label>World ID<input value={world} onChange={e=>setWorld(e.target.value)} placeholder="default or team-…"/></label><p>The control console requires the operator token. Team keys work on the other sites and can control their own clock.</p></section>}
      {view.error&&<p className="error" role="alert">{view.error.message}</p>}
      {view.data&&<><section className="clock"><div><small>SIMULATION TIME · UTC</small><strong>{new Date(view.data.now).toISOString().replace('T',' ').slice(0,19)}</strong><span>{view.data.paused?'Paused':'Running'} · {view.data.speed}×</span></div><button disabled={mutation.isPending} onClick={()=>clock({paused:!view.data!.paused})}>{view.data.paused?'▶ Run':'Ⅱ Pause'}</button><label>Speed<select value={view.data.speed} onChange={e=>clock({speed:Number(e.target.value)})}>{[1,10,60,300,3600].map(v=><option key={v} value={v}>{v}×</option>)}</select></label><button disabled={!view.data.paused||mutation.isPending} onClick={()=>clock({advanceMinutes:60})}>Step 1 hour</button></section>
      <section className="metrics"><article><small>Population</small><strong>{view.data.population.toLocaleString()}</strong></article><article><small>Visible work items</small><strong>{rows.length}</strong></article><article><small>Completed actions</small><strong>{view.data.counters.completed}</strong></article><article><small>A&E staffed spaces</small><strong>{view.data.staffing.staffedSpaces}</strong><span>{view.data.staffing.doctors} doctors / {view.data.staffing.nurses} nurses</span></article></section>
      {siteId==='control'&&<section className="panel"><h2>World agents & incidents</h2><div className="chips">{view.data.agents?.map(a=><button key={a.id} onClick={()=>mutation.mutate({path:'/api/control/agents'+suffix,data:{id:a.id,enabled:!a.enabled}})}>{a.enabled?'On':'Off'} · {a.id}</button>)}</div><div className="api-grid">{scenarios.map(s=><article key={s.id}><h3>{s.title}</h3><p>{s.description}</p><button onClick={()=>mutation.mutate({path:'/api/control/incidents'+suffix,data:{id:s.id,enabled:!view.data!.faults?.[s.id]}})}>{view.data?.faults?.[s.id]?'Restore':'Inject'}</button></article>)}</div><button onClick={async()=>{try{const result=await api('/api/control/model-propose'+suffix,{});setNotice(JSON.stringify(result));}catch(e){setNotice((e as Error).message);}}}>Ask optional model agent for task proposals</button></section>}
      <section className="panel"><div className="section-heading"><h2>Patient workspace</h2><label>Find patient<input placeholder="Name or SIM identifier" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><label>Patient<select value={patient} onChange={e=>setPatient(e.target.value)}><option value="">All visible work</option>{patients.data?.items.map(p=><option value={p.id} key={p.id}>{p.name} · {p.id}</option>)}</select></label>{current&&<div className="patient"><h3>{current.name}</h3><p>{current.conditions.join(' · ')}</p><p>Access needs: {current.needs.join(', ')}</p><p>Goals: {current.goals.join('; ')}</p><div className="chips">{sites.filter(s=>!['control',siteId].includes(s.id)).map(s=><a key={s.id} href={'/'+s.id+'/?patient='+patient}>{s.name}</a>)}</div></div>}
      {patient&&<form onSubmit={e=>{e.preventDefault();mutation.mutate({path:'/api/sites/'+siteId+'/actions'+suffix,data:{type:actionType,patientId:patient,title}});}}><label>Action<select value={actionType} onChange={e=>setActionType(e.target.value as Action['type'])}>{['create_task','create_referral','order_test','draft_prescription','book_appointment','send_message','schedule_visit','dispatch_robot'].map(t=><option value={t} key={t}>{t.replaceAll('_',' ')}</option>)}</select></label><label>Reason / description<input value={title} onChange={e=>setTitle(e.target.value)} required maxLength={500}/></label><button disabled={mutation.isPending}>Submit action</button></form>}</section>
      <section className="panel"><h2>{siteId==='roster'?'Roster & skill mix':siteId==='hr'?'Staff & absence':siteId==='wearables'?'Signals & devices':siteId==='robotics'?'Fleet & jobs':'Operational worklist'}</h2><div className="table-wrap"><table><thead><tr><th>Record</th><th>Patient / owner</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><small>{r.kind} · {r.id} · v{r.version}</small><strong>{r.title}</strong><details><summary>Record details</summary><pre>{JSON.stringify(r.data,null,2)}</pre></details></td><td>{r.patientId??'System'}<br/><small>{r.owner}</small></td><td><span className={'status '+r.status}>{r.status}</span></td><td><div className="row-actions">{r.kind==='staff'?<><button onClick={()=>act(r.status==='absent'?'restore_staff':'report_absence',r)}>{r.status==='absent'?'Return':'Report absence'}</button><button onClick={()=>act('allocate_shift',r)}>{r.data.allocated?'Remove shift':'Allocate shift'}</button></>:<>{['open','draft','available'].includes(r.status)&&<button onClick={()=>act('review',r)}>Review</button>}{['open','reviewed','rejected'].includes(r.status)&&<button onClick={()=>act('accept',r)}>Accept</button>}{['open','reviewed','accepted','scheduled','waiting'].includes(r.status)&&<button onClick={()=>act('complete',r)}>Complete</button>}{r.kind==='prescription'&&r.status==='approved'&&<button onClick={()=>act('dispense',r)}>Dispense</button>}{r.kind==='prescription'&&r.status==='dispensed'&&<button onClick={()=>act('collect',r)}>Collect</button>}<button onClick={()=>act('share_record',r,'gp')}>Share with GP</button></>}</div></td></tr>)}</tbody></table>{rows.length===0&&<p>No visible records for this selection. Use an action to start a workflow.</p>}</div></section>
      <section className="panel"><h2>Activity trail</h2>{view.data.events.length===0?<p>No events yet. Start the clock or submit an action.</p>:<ol className="events">{view.data.events.slice(0,20).map(e=><li key={e.id}><time>{new Date(e.time).toISOString().slice(11,19)}</time><strong>{e.type}</strong><span>{e.detail}</span><small>{e.actor}</small></li>)}</ol>}</section></>}
      {siteId==='legacy'&&key&&<section className="panel"><h2>Browser-only record system</h2><p>No public data API. Use the HTML workflow below; automation tools can inspect the document table and submit its form.</p><button onClick={async()=>{try{await api('/api/session',{});setBrowserReady(true);}catch(e){setNotice((e as Error).message);}}}>Open legacy session</button>{browserReady&&<iframe title="Legacy EPR" src="/browser/legacy"/>}</section>}
      </>}
    </main>
  </div>;
}
