import React, { useState, useEffect, useRef } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { Patient, Resource } from "../../contracts/src/index.ts";
import { conversationSchema, messageTemplateSchema, type MessagingCommand } from "../../contracts/src/messaging.ts";
import type { WorkflowApi } from "./gp-workflows.tsx";
import { ProductBrand } from "./product-brand.tsx";
import "./messaging-workspace.css";
type Props = { api: WorkflowApi; worldId: string; selectedPatient: string; patients: Patient[]; patientMatches: Patient[]; patientSearch: string; searchPatients: (value: string) => void; selectPatient: (id: string) => void; role?: "practice" | "patient" };
type Inbox = { resources: Resource[]; patients: Patient[] };
const date = (time: number) => new Date(time).toLocaleString("en-GB", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit", timeZone: "UTC" });
export function MessagingWorkspace(props: Props) {
  const patientMode = props.role === "patient";
  const site = patientMode ? "patient" : "gp";
  const client = useQueryClient();
  const [selected, setSelected] = useState("");
  const [tab, setTab] = useState("inbox");
  const [search, setSearch] = useState("");
  const [newMessage, setNewMessage] = useState(false);
  const [notice, setNotice] = useState("");
  const [composerRevision, setComposerRevision] = useState(0);
  const [patientThreadOpen, setPatientThreadOpen] = useState(false);
  const queryKey = ["messaging", props.worldId, site, patientMode ? props.selectedPatient : "all"];
  const data = useQuery({ queryKey, queryFn: () => props.api<Inbox>(`/api/sites/${site}/messaging-workspace${patientMode ? `?patientId=${encodeURIComponent(props.selectedPatient)}` : ""}`), enabled: !patientMode || Boolean(props.selectedPatient), refetchInterval: 5000 });
  const mutation = useMutation({ mutationFn: ({ command, resource, patientId }: { command: MessagingCommand; resource?: Resource; patientId?: string }) => props.api<Resource>(`/api/sites/${site}/actions`, { type: "messaging_action", messagingCommand: command, ...(resource ? { resourceId: resource.id, expectedVersion: resource.version } : {}), ...(patientId ? { patientId } : {}) }), onSuccess: (r, input) => { if (["send", "reply", "note"].includes(input.command.kind)) setComposerRevision(value => value + 1); client.setQueryData<Inbox>(queryKey, old => old ? { ...old, resources: old.resources.some(item => item.id === r.id) ? old.resources.map(item => item.id === r.id ? r : item) : [r, ...old.resources] } : old); setSelected(r.id); setNewMessage(false); setNotice(input.command.kind === "create" || input.command.kind === "send" ? "Message queued in the simulator. Open Delivery simulator to deliver it or test a failure." : input.command.kind === "reply" ? "Reply sent to the practice inbox." : "Saved to your team world."); void client.invalidateQueries(); } });
  const names = new Map([...props.patients, ...(data.data?.patients ?? [])].map(patient => [patient.id, patient.name]));
  const all = data.data?.resources ?? [];
  const templates = all.filter(r => r.kind === "message-template" && r.status === "active");
  const conversations = all.filter(r => r.kind === "conversation");
  const rows = conversations.filter(r => (patientMode || r.status === (tab === "done" ? "done" : "open")) && `${r.title} ${names.get(r.patientId ?? "")} ${r.patientId}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => (conversationSchema.safeParse(b.data).data?.entries.at(-1)?.at ?? b.createdAt) - (conversationSchema.safeParse(a.data).data?.entries.at(-1)?.at ?? a.createdAt));
  const current = rows.find(r => r.id === selected) ?? rows[0];
  const parsed = current ? conversationSchema.safeParse(current.data) : undefined;
  const doc = parsed?.success ? parsed.data : null;
  const send = (command: MessagingCommand, resource = current) => mutation.mutate({ command, resource, ...(patientMode ? { patientId: props.selectedPatient } : {}) });
  const patientTimeline = useRef<HTMLDivElement>(null);
  useEffect(() => { if (patientMode && patientTimeline.current) patientTimeline.current.scrollTop = patientTimeline.current.scrollHeight; }, [patientMode, patientThreadOpen, current?.id, doc?.entries.length]);
  if (patientMode) return <section className={`ios-messages ${patientThreadOpen ? "ios-show-thread" : ""}`} aria-label="Patient messages">
    <header className="ios-app-bar"><a href={`/control/?place=home`}>‹ Home</a><details><summary>{names.get(props.selectedPatient) ?? "Choose patient"} <span>⌄</span></summary><PatientPicker {...props} selectPatient={id => { props.selectPatient(id); setSelected(""); setPatientThreadOpen(false); }} /></details><a href={`/wearables/?patient=${encodeURIComponent(props.selectedPatient)}`}>Health</a></header>
    <div className="ios-split"><aside className="ios-conversations"><h1>Messages</h1><label className="ios-search"><span>⌕</span><input aria-label="Search conversations" placeholder="Search" value={search} onChange={e => setSearch(e.target.value)} /></label><p className="ios-inbox-caption">Practice conversations</p>{data.isPending && props.selectedPatient && <p>Loading messages…</p>}{rows.map(r => { const entries = conversationSchema.parse(r.data).entries; return <button className={`ios-conversation ${r.id === current?.id ? "ios-selected" : ""}`} key={r.id} onClick={() => { setSelected(r.id); setPatientThreadOpen(true); }}><span className="ios-avatar">RP</span><span className="ios-conversation-copy"><span><strong>Riverside Practice</strong><time>{date(entries.at(-1)?.at ?? r.createdAt)} ›</time></span><b>{r.title}</b><span>{entries.at(-1)?.body}</span></span></button>; })}{!data.isPending && !rows.length && <p className="ios-empty">No messages yet. Delivered practice messages appear here.</p>}</aside>
    <main className="ios-chat">{current && doc ? <><header className="ios-chat-header"><button className="ios-back" onClick={() => setPatientThreadOpen(false)} aria-label="Back to messages">‹ <span>Messages</span></button><div><span className="ios-avatar">RP</span><strong>Riverside Practice <span>›</span></strong></div><details><summary aria-label="Conversation details">ⓘ</summary><p>{current.title}</p><p>{current.status === "done" ? "Completed" : doc.allowReply ? "Replies enabled" : "Replies disabled"}</p></details></header><div className="ios-chat-scroll" ref={patientTimeline}><p className="ios-conversation-title">{current.title}</p>{doc.entries.map(entry => <article key={entry.id} className={`ios-message ${entry.direction === "incoming" ? "ios-from-me" : "ios-from-practice"}`}><time>{date(entry.at)}</time><p>{entry.body}</p><small>{entry.direction === "incoming" ? "Sent" : entry.actor.name}</small></article>)}</div>{mutation.isError && <p className="ios-error" role="alert">{mutation.error.message}</p>}{current.status === "open" && doc.allowReply ? <PatientReply key={`${current.id}-${composerRevision}`} pending={mutation.isPending} save={body => send({ kind: "reply", body })} /> : <p className="ios-replies-off">{current.status === "done" ? "This conversation is completed." : "The practice has turned off replies."}</p>}</> : <div className="ios-empty"><span>•••</span><h2>Your conversations</h2><p>Choose a patient and open a message.</p></div>}</main></div>{data.isError && <p className="ios-error" role="alert">{data.error.message} <button onClick={() => void data.refetch()}>Try again</button></p>}
  </section>;
  return <section className={`messaging-workspace${patientMode ? " messaging-patient" : ""}`} aria-label={patientMode ? "Patient messages" : "InaccuRx messaging"}>
    <header className="messaging-header"><div>{patientMode ? <><span className="messages-app-icon">•••</span><strong>Messages</strong></> : <ProductBrand product="messaging" />}<small>{patientMode ? "Your practice, in your pocket" : "Riverside Practice · patient conversations"}</small></div><nav><a href={patientMode ? `/wearables/?patient=${encodeURIComponent(props.selectedPatient)}` : `/gp/?patient=${encodeURIComponent(props.selectedPatient)}`}>{patientMode ? "Home & health" : "SystemTwo"} ↗</a>{!patientMode && <a href={`/gp/documents/?patient=${encodeURIComponent(props.selectedPatient)}`}>DocuMañana ↗</a>}<a href="/control/">Neighbourhood</a></nav></header>
    {patientMode && <div className="messaging-patient-picker"><PatientPicker {...props} /><p>Viewing {names.get(props.selectedPatient) ?? "no patient selected"}. All messages stay inside this simulation.</p></div>}
    <div className="messaging-toolbar">{!patientMode && <><nav aria-label="Messaging folders">{["inbox", "done", "templates"].map(value => <button key={value} aria-pressed={tab === value} onClick={() => { setTab(value); setNewMessage(false); setSelected(""); }}>{value === "inbox" ? `Inbox (${conversations.filter(r => r.status === "open").length})` : value === "done" ? "Done" : "Templates"}</button>)}</nav><button className="messaging-primary" onClick={() => { setNewMessage(true); setTab("inbox"); }}>＋ New message</button></>}{patientMode && <h1>Your conversations</h1>}</div>
    {data.isError && <p role="alert">{data.error.message} <button onClick={() => void data.refetch()}>Try again</button></p>}{mutation.isError && <p role="alert">{mutation.error.message}</p>}{notice && <p className="messaging-notice" role="status">{notice}</p>}
    {tab === "templates" && !patientMode ? <Templates key={templates.map(r => `${r.id}-${r.version}`).join()} templates={templates} pending={mutation.isPending} save={(command, resource) => mutation.mutate({ command, resource })} /> : <div className="messaging-columns"><aside className="messaging-inbox"><label>Search conversations<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Patient or subject" /></label>{data.isPending && (props.selectedPatient || !patientMode) && <p>Loading conversations…</p>}{rows.map(r => { const value = conversationSchema.safeParse(r.data); const last = value.success ? value.data.entries.at(-1) : undefined; return <button key={r.id} className={r.id === current?.id && !newMessage ? "selected" : ""} onClick={() => { setSelected(r.id); setNewMessage(false); setNotice(""); }}><span className="messaging-row-heading"><strong>{patientMode ? "Riverside Practice" : names.get(r.patientId ?? "") ?? r.patientId}</strong><small>{date(last?.at ?? r.createdAt)}</small></span><b>{r.title}</b><span>{last?.body}</span>{!patientMode && <small>{r.status === "done" ? "Completed" : value.success && value.data.assignee ? value.data.assignee : "Unassigned"}</small>}</button>; })}{!data.isPending && !rows.length && <p>No conversations here yet.</p>}</aside>
      <main className="messaging-thread">{newMessage ? <NewMessage {...props} key={props.selectedPatient} templates={templates} pending={mutation.isPending} save={command => mutation.mutate({ command, patientId: props.selectedPatient })} cancel={() => setNewMessage(false)} /> : current && doc ? <><header className="messaging-thread-header"><div><small>{patientMode ? "Riverside Practice" : names.get(current.patientId ?? "") ?? current.patientId}</small><h1>{current.title}</h1><span>{current.status === "done" ? "Conversation completed" : "Open conversation"} · {doc.allowReply ? "Replies enabled" : "One-way message"}</span></div>{!patientMode && <button disabled={mutation.isPending} onClick={() => send({ kind: current.status === "done" ? "reopen" : "complete" })}>{current.status === "done" ? "Reopen" : "Mark done"}</button>}</header>
        {!patientMode && <details className="messaging-context"><summary>Patient & assignment</summary><p>{names.get(current.patientId ?? "")} · {current.patientId} <a href={`/gp/?patient=${encodeURIComponent(current.patientId ?? "")}`}>Open patient record ↗</a></p><Assignment key={`${current.id}-${doc.assignee}`} initial={doc.assignee} pending={mutation.isPending} save={assignee => send({ kind: "assign", assignee })} /></details>}
        <div className="messaging-timeline">{doc.entries.map(entry => <article className={`messaging-bubble messaging-${entry.direction}`} key={entry.id}><div><strong>{entry.direction === "internal" ? "Internal note" : entry.direction === "incoming" ? patientMode ? "You" : names.get(current.patientId ?? "") ?? "Patient" : entry.actor.name}</strong><small>{date(entry.at)} UTC{entry.direction !== "internal" ? ` · ${entry.channel.toUpperCase()}` : " · Practice only"}{entry.direction === "incoming" && !patientMode ? ` · Entered by ${entry.actor.name}` : ""}</small></div><p>{entry.body}</p>{entry.direction === "outgoing" && !patientMode && <span className={`messaging-delivery messaging-${entry.delivery.at(-1)?.status}`}>{entry.delivery.at(-1)?.status} · attempt {entry.delivery.filter(event => event.status === "queued").length}</span>}</article>)}</div>
        {current.status === "open" && (!patientMode || doc.allowReply) ? <Composer key={`${current.id}-${composerRevision}`} patientMode={patientMode} templates={templates} pending={mutation.isPending} save={send} /> : <p className="messaging-closed">{current.status === "done" ? "This conversation is completed." : "Replies are turned off for this conversation. Contact the practice through another simulated channel."}</p>}
        {!patientMode && <details className="messaging-simulator"><summary>Delivery simulator</summary><p>Nothing is sent to a real phone or email address. Select a delivery outcome, then open Messages at the patient's home to reply.</p>{doc.entries.filter(entry => entry.direction === "outgoing").map(entry => entry.direction === "outgoing" && <div className="messaging-sim-row" key={entry.id}><span>{entry.body.slice(0, 65)}… <b>{entry.delivery.at(-1)?.status}</b></span>{entry.delivery.at(-1)?.status === "queued" ? <><button disabled={mutation.isPending} onClick={() => send({ kind: "delivery", entryId: entry.id, status: "delivered" })}>Deliver</button><button disabled={mutation.isPending} onClick={() => send({ kind: "delivery", entryId: entry.id, status: "failed" })}>Fail delivery</button></> : entry.delivery.at(-1)?.status === "failed" ? <button disabled={mutation.isPending} onClick={() => send({ kind: "retry", entryId: entry.id })}>Retry delivery</button> : <span>Delivered</span>}<details><summary>Delivery history</summary>{entry.delivery.map((event, index) => <small key={index}>{date(event.at)} · {event.status} · {event.actor.name}</small>)}</details></div>)}<a href={`/wearables/messages/?patient=${encodeURIComponent(current.patientId ?? "")}`}>Open this patient's Messages app ↗</a></details>}
      </> : <div className="messaging-empty"><span>•••</span><h2>{patientMode ? "Your practice messages live here" : "Start a conversation"}</h2><p>{patientMode ? "Choose a patient to see their delivered messages." : "Choose a conversation or send a new patient message."}</p></div>}</main></div>}
  </section>;
}
function PatientPicker(props: Props) { return <div className="messaging-patient-search"><label>Find patient<input value={props.patientSearch} placeholder="Name or patient ID" onChange={e => props.searchPatients(e.target.value)} /></label>{props.patientSearch && <div className="messaging-patient-results">{props.patientMatches.map(p => <button key={p.id} onClick={() => { props.selectPatient(p.id); props.searchPatients(""); }}>{p.name} · {p.id}</button>)}</div>}</div>; }
function Assignment({ initial, pending, save }: { initial: string; pending: boolean; save: (value: string) => void }) { const [value, setValue] = useState(initial); return <form onSubmit={e => { e.preventDefault(); save(value); }}><label>Assigned to<input value={value} maxLength={120} placeholder="Clinician or team" onChange={e => setValue(e.target.value)} /></label><button disabled={pending}>Save assignment</button></form>; }
function NewMessage(props: Props & { templates: Resource[]; pending: boolean; save: (command: MessagingCommand) => void; cancel: () => void }) {
  const [subject, setSubject] = useState(""); const [body, setBody] = useState(""); const [channel, setChannel] = useState<"sms" | "email">("sms"); const [allowReply, setAllowReply] = useState(true);
  const name = [...props.patients, ...props.patientMatches].find(p => p.id === props.selectedPatient)?.name ?? props.selectedPatient;
  return <form className="messaging-new" onSubmit={e => { e.preventDefault(); props.save({ kind: "create", subject, body, channel, allowReply }); }}><h1>New patient message</h1><PatientPicker {...props} /><p>To <strong>{name || "Choose a patient above"}</strong></p><label>Subject<input required maxLength={160} value={subject} onChange={e => setSubject(e.target.value)} /></label><TemplatePicker templates={props.templates} apply={(text, route) => { setBody(text); setChannel(route); }} /><label>Channel<select value={channel} onChange={e => setChannel(e.target.value === "email" ? "email" : "sms")}><option value="sms">SMS</option><option value="email">Email</option></select></label><label>Message<textarea required rows={7} maxLength={5000} value={body} onChange={e => setBody(e.target.value)} /></label><label className="messaging-checkbox"><input type="checkbox" checked={allowReply} onChange={e => setAllowReply(e.target.checked)} /> Allow patient replies</label><p>Queued messages appear in the patient's app once delivered using the simulator.</p><button className="messaging-primary" disabled={props.pending || !props.selectedPatient}>Queue message</button> <button type="button" onClick={props.cancel}>Cancel</button></form>;
}
function TemplatePicker({ templates, apply }: { templates: Resource[]; apply: (body: string, channel: "sms" | "email") => void }) { return <label>Use a template<select value="" onChange={e => { const resource = templates.find(r => r.id === e.target.value); const parsed = messageTemplateSchema.safeParse(resource?.data); if (parsed.success) apply(parsed.data.body, parsed.data.channel); }}><option value="">Choose a template…</option>{templates.map(r => <option key={r.id} value={r.id}>{r.title}</option>)}</select></label>; }
function Composer({ patientMode, templates, pending, save }: { patientMode: boolean; templates: Resource[]; pending: boolean; save: (command: MessagingCommand) => void }) { const [body, setBody] = useState(""); const [channel, setChannel] = useState<"sms" | "email">("sms"); const [note, setNote] = useState(false); return <form className="messaging-composer" onSubmit={e => { e.preventDefault(); save(patientMode ? { kind: "reply", body } : note ? { kind: "note", body } : { kind: "send", body, channel }); }}><div>{!patientMode && <><TemplatePicker templates={templates} apply={(text, route) => { setBody(text); setChannel(route); }} /><label>Message type<select value={note ? "note" : channel} onChange={e => { setNote(e.target.value === "note"); if (e.target.value !== "note") setChannel(e.target.value === "email" ? "email" : "sms"); }}><option value="sms">SMS</option><option value="email">Email</option><option value="note">Internal note</option></select></label></>}</div><label>{patientMode ? "Your reply" : note ? "Practice-only note" : "Message to patient"}<textarea required maxLength={5000} rows={3} value={body} onChange={e => setBody(e.target.value)} /></label><button className="messaging-primary" disabled={pending || !body.trim()}>{patientMode ? "Send reply" : note ? "Add internal note" : "Queue message"}</button></form>; }
function Templates({ templates, pending, save }: { templates: Resource[]; pending: boolean; save: (command: MessagingCommand, resource?: Resource) => void }) { const [selected, setSelected] = useState<Resource>(); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [channel, setChannel] = useState<"sms" | "email">("sms"); return <div className="messaging-templates"><aside><h2>Practice templates</h2><button onClick={() => { setSelected(undefined); setTitle(""); setBody(""); }}>＋ New template</button>{templates.map(r => <button key={r.id} onClick={() => { const parsed = messageTemplateSchema.parse(r.data); setSelected(r); setTitle(r.title); setBody(parsed.body); setChannel(parsed.channel); }}>{r.title}</button>)}</aside><form onSubmit={e => { e.preventDefault(); save({ kind: "save_template", title, body, channel }, selected); }}><h2>{selected ? "Edit template" : "New template"}</h2><label>Template name<input required value={title} maxLength={120} onChange={e => setTitle(e.target.value)} /></label><label>Channel<select value={channel} onChange={e => setChannel(e.target.value === "email" ? "email" : "sms")}><option value="sms">SMS</option><option value="email">Email</option></select></label><label>Template text<textarea required rows={8} value={body} maxLength={5000} onChange={e => setBody(e.target.value)} /></label><button className="messaging-primary" disabled={pending}>Save template</button>{selected && <button type="button" disabled={pending} onClick={() => save({ kind: "archive_template" }, selected)}>Archive template</button>}</form></div>; }

function PatientReply({ pending, save }: { pending: boolean; save: (body: string) => void }) {
  const [body, setBody] = useState("");
  return <form className="ios-reply" onSubmit={e => { e.preventDefault(); save(body); }}><label><span className="ios-sr-only">Your reply</span><textarea aria-label="Your reply" placeholder="Text Message" rows={1} maxLength={5000} required value={body} onChange={e => setBody(e.target.value)} /></label><button aria-label="Send reply" disabled={pending || !body.trim()}>{pending ? "…" : "↑"}</button></form>;
}
